### ISSUE TITLE
My terminal doesn't like "●"

### ISSUE THREAD

**Issue by dakotahawkins** [Aearnus/cherchord#3]
```
$ cherchord Emaj -f 4
found 140 unique fingerings for the chord Emaj ([E,Ab,B])
printing out 140 of them...

E A D G B E   E A D G B E   E A D G B E
0 2 2 1 0 0   0 2 2 1 0 4   0 2 2 4 0 0
- - - - - -   - - - - - -   - - - - - -
| | | cherchord.exe: <stdout>: commitBuffer: invalid argument (invalid character)
```

This is using the Git for Windows bash, but it might be worthwhile in any case to try to detect support or use a different character (tested with `o`, that works fine and looks worse-but-not-awful).

**Comment by DataKinds** [comment]
Are you using this through the command prompt or through the fancy new WSL beta terminal?

**Comment by dakotahawkins** [comment]
Neither, exactly, though I assume there are other real terminals that don't support unicode.

Edit: The terminal is based on msys2 which is based on cygwin, and it comes with what you get when you install "Git for Windows". I'm actually using _that_ through a different terminal utility but was able to reproduce it in the regular one, so I didn't want to confuse the issue.

I found a way to detect support for unicode but my knowledge of Haskell is super limited so I didn't get it working.

**Comment by DataKinds** [comment]
Decided to fix this by dropping the fancy symbol and using a lowercase "o". Keeping it old school. 76e749ee648473ab47655e0b25c9fe52b7b10ce2
